version: "3.3"

services:
  reverse_proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse_proxy
    restart: always
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"

  frontend_website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: frontend_website
    restart: always
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - frontend
    ports:
      - "8002:80"

networks:
  frontend:
